export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_PROFILE_USER = 'GET_PROFILE_USER'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'

export const GET_ANNANCE = 'GET_ANNANCE'
export const GET_ANNANCE_FAIL = 'GET_ANNANCE_FAIL'
export const GET_ANNANCE_SUCCESS = 'GET_ANNANCE_SUCCESS'

export const NEW_ANNANCE = 'NEW_ANNANCE'
export const NEW_ANNANCE_FAIL = 'NEW_ANNANCE_FAIL'
export const NEW_ANNANCE_SUCCESS = 'NEW_ANNANCE_SUCCESS'

export const DELETE_ANNANCE = 'DELETE_ANNANCE'
export const DELETE_ANNANCE_FAIL = 'DELETE_ANNANCE_FAIL'
export const DELETE_ANNANCE_SUCCESS = 'DELETE_ANNANCE_SUCCESS'

export const MODIF_ANNANCE = 'MODIF_ANNANCE'
export const MODIF_ANNANCE_FAIL = 'MODIF_ANNANCE_FAIL'
export const MODIF_ANNANCE_SUCCESS = 'MODIF_ANNANCE_SUCCESS'


export const GET_ALL_USERS = 'GET_ALL_USERS'
export const BLOCK_USER = 'BLOCK_USER'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const LOGOUT = 'LOGOUT'
export const GET_ELEMENTS='GET_ELEMENTS'
export const GET_NUMBER='GET_NUMBER'